algorithm:
  servername: 'ServerFedAvg'
  clientname: 'ClientOptim'
  args:
    ## Server update
    # server_learning_rate: 0.01
    server_adapt_param: 0.000
    # server_momentum_param_1: 0.9
    # server_momentum_param_2: 0.99
    ## Clients optimizer
    optim: "Adam"
    num_local_epochs: 2
    optim_args: 
        lr: 0.0004
    server_lr_decay_exp_gamma : 0.975   
    ## Differential Privacy
    epsilon: False
    ## Gradient Clipping
    ## clip_value: 1
    clip_value: False
    clip_norm: 1
    client_weights: "sample_size"

model:
  num_output: 2

training:
  num_epochs: 30
  save_model_filename: "Covid_Resnet"

dataset:
  name: CovidDataset

func:
  get_model:
    script_file: "./models/resnet.py"
    call: "get_model"