clients:
  - endpoint_id: "0499500d-2f18-4a67-9ef8-419053d3a18a"  # Replace with your Globus Compute endpoint ID
    client_id: "Client1"
    train_configs:
      # Device [Optional]: default is "cpu"
      device: "cpu"
      # Logging [Optional]
      logging_output_dirname: "./output"
      logging_output_filename: "client_1_result"

    # Local dataset
    data_configs:
      dataset_path: "./resources/dataset/cora_dataset.py"
      dataset_name: "get_cora"
      dataset_kwargs:
        num_clients: 1
        client_id: 0
        partition_strategy: "random"  # Options: "random", "label_skew"
        # alpha: 0.5  # For label_skew strategy (lower = more non-IID)
        visualization: True

  # - endpoint_id: "YOUR_ENDPOINT_ID_2"  # Replace with your Globus Compute endpoint ID
  #   client_id: "Client2"
  #   train_configs:
  #     # Device [Optional]: default is "cpu"
  #     device: "cpu"
  #     # Logging [Optional]
  #     logging_output_dirname: "./output"
  #     logging_output_filename: "client_2_result"

  #   # Local dataset
  #   data_configs:
  #     dataset_path: "./resources/dataset/cora_dataset.py"
  #     dataset_name: "get_cora"
  #     dataset_kwargs:
  #       num_clients: 2
  #       client_id: 1
  #       partition_strategy: "random"
  #       visualization: False
