client_configs:
  train_configs:
    # Local trainer
    trainer: "VanillaTrainer"
    mode: "step"
    num_local_steps: 100
    optim: "Adam"
    optim_args:
      lr: 0.001
    # Loss function
    loss_fn_path: "./resources/loss/celoss.py"
    loss_fn_name: "CELoss"
    # Client validation
    do_validation: True
    do_pre_validation: True
    metric_path: "./resources/metric/acc.py"
    metric_name: "accuracy"
    # Differential privacy
    use_dp: False
    epsilon: 1
    clip_grad: False
    clip_value: 1
    clip_norm: 1
    # Data format
    send_gradient: True
    # Data loader
    train_batch_size: 64
    val_batch_size: 64
    train_data_shuffle: True
    val_data_shuffle: False

  model_configs:
    model_path: "./resources/model/cnn.py"
    model_name: "CNN"
    model_kwargs:
      num_channel: 1
      num_classes: 10
      num_pixel: 28

server_configs:
  num_clients: 2
  scheduler: "QueueScheduler"
  scheduler_kwargs:
    t_sync: 6
    lr_base: 0.001
    warm_up_steps: 20
    alpha_queue: 0.5
    alpha_compute: 0.5
    safety_buffer: 0.3
    admission_tolerance: 0.15

  aggregator: "FedQueueAggregator"
  aggregator_kwargs:
    weights: "equal"
    staleness_fn: "harmonic"
    staleness_fn_kwargs:
      beta: 0.5
  device: "cpu"
  num_global_epochs: 20
  logging_output_dirname: "./output"
  logging_output_filename: "result"
  comm_configs:
    grpc_configs:
      server_uri: localhost:50051
      max_message_size: 1048576
      use_ssl: False
