seed: 42
data:
  networks: ["case30_ieee_large"]
  scenarios: [275000]
  normalization: "baseMVAnorm"
  baseMVA: 100
  mask_type: "rnd"
  mask_value: 0.0
  mask_ratio: 0.5
  mask_dim: 6
  learn_mask: False
  val_ratio: 0.1
  test_ratio: 0.1
  workers: 16
model:
  attention_head: 8
  dropout: 0.1
  edge_dim: 2
  hidden_size: 256
  input_dim: 9
  num_layers: 8
  output_dim: 6
  pe_dim: 20
  type: GPSTransformer
training:
  batch_size: 16
  losses: ["MaskedMSE", "PBE"]
  loss_weights: [0.01, 0.99]
  accelerator: auto
  devices: auto
  strategy: auto
